// Precompute the wing-fold solution (src/birds/kentishPlover/anatomy/wingFold.js) and write it to
// wingFold.cache.js, keyed by the solver version, the wing layout and the body outline.
// usage: node tools/dev/wingfold-cache.mjs          regenerate
//        node tools/dev/wingfold-cache.mjs --check  exit 1 if the cache is out of date
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { KentishPloverConfig as CFG } from '../../src/birds/kentishPlover/KentishPloverConfig.js';
import { getSpec } from '../../src/birds/kentishPlover/KentishPloverModel.js';
import { getBodySDF, getTorsoSDF } from '../../src/birds/kentishPlover/anatomy/bodyMesh.js';
import { computeWingFold, serializeWingFold, wingFoldKey } from '../../src/birds/kentishPlover/anatomy/wingFold.js';
import PRECOMPUTED from '../../src/birds/kentishPlover/anatomy/wingFold.cache.js';

const spec = getSpec();
const sdf = getBodySDF(CFG);
const torso = getTorsoSDF(CFG, { trunkOnly: true });
const key = wingFoldKey(spec.wingFeathers, sdf, torso);
if (process.argv.includes('--check')) {
  const ok = PRECOMPUTED.key === key;
  console.log(ok ? `wing fold cache up to date (${key})` : `wing fold cache out of date (${PRECOMPUTED.key || 'empty'} ≠ ${key}): run node tools/dev/wingfold-cache.mjs`);
  process.exit(ok ? 0 : 1);
}
const t0 = performance.now();
const fold = computeWingFold(spec.wingFeathers, sdf, torso, { useCache: false });
const ms = performance.now() - t0;
const out = fileURLToPath(new URL('../../src/birds/kentishPlover/anatomy/wingFold.cache.js', import.meta.url));
const text = `// Generated by tools/dev/wingfold-cache.mjs — do not edit.\nexport default ${JSON.stringify({ key, data: serializeWingFold(fold) })};\n`;
writeFileSync(out, text);
console.log(`wing fold solved in ${ms.toFixed(0)} ms, cache ${key} written (${(text.length / 1024).toFixed(0)} KiB)`);
